CXXFLAGS = -I/usr/src -DVERSION="\"0.0.1\""
EXTERN_LIBS =	-L/usr/X11R6/lib -lz -lX11 -lXext -lvga /usr/lib/libz.a

objs = pingus.o    \
       game.o      \
       level.o     \
       playfield.o \
       gui_obj.o   \
       world.o     \
       pingu.o     \
#       init.o      \
 #      intro.o     \



pingus.exe : $(objs)
	g++ $(objs) -lclan -ldl  $(EXTERN_LIBS) -o pingus

clean : 
	rm $(objs) pingus
